services:
  db:
    image: postgres:15-alpine
    container_name: sihealth-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=suasenha123
      - POSTGRES_DB=SiHealth
    ports:
      - "4001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: